### ISSUE TITLE
Unable to load store and forward items from DB in Store and Forward

### ISSUE THREAD

**Issue by iamonlysaiful** [edgexfoundry/app-service-configurable#300] opened 2021-07-16 05:58 UTC
#help 
Please Help...
I running EdgeX Foundry from docker container...

I am getting this error continiously in my edgex-app-service-configurable-rules docker cotainer console,

```
level=ERROR ts=2021-07-16T05:11:19.3445987Z app=AppService-http-export source=storeforward.go:136 error="Could not dial Redis: dial tcp 127.0.0.1:6379: connect: connection refused" msg="Unable to load store and forward items from DB"
```

When my setup for **[Writable.StoreAndForward]** are like this 
```  
[Writable.StoreAndForward]
    Enabled = "true"
    MaxRetryCount = "10"
    RetryInterval = "1m"
```

and **[Database]** section,
```
[Database]
  BatchSize = "0"
  Host = "localhost"
  MaxIdle = "0"
  Password = ""
  Port = "6379"
  Timeout = "30s"
  Type = "redisdb"
  Username = ""
```

and **[Writable.InsecureSecrets]** section,
```
[Writable.InsecureSecrets]

    [Writable.InsecureSecrets.DB]
      Path = "redisdb"

      [Writable.InsecureSecrets.DB.Secrets]
        password = ""
        username = ""

    [Writable.InsecureSecrets.http]
      Path = "http"

      [Writable.InsecureSecrets.http.Secrets]
        yoursecretheadername = ""
```

**Comment by lenny-intel** [comment] 2021-07-16 16:00
This a duplicate of question in Slack. Question is being addressed in slack.

**Closed by lenny-intel** 2021-07-16 16:00 UTC

**Comment by iamonlysaiful** [comment] 2021-07-19 04:42
But problem is still there @lenny-intel
